import Head from 'next/head'
import { SideNavigation, TopNavigation } from '../components'
import { Table } from '../components'


export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to Balushai Vendor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="/assets/fa/css/all.min.css"
          id="app-style"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="/assets/fa/css/fontawesome.min.css"
          id="app-style"
          rel="stylesheet"
          type="text/css"
        />
      </Head>

      <div className='flex w-screen min-h-screen'>
        <SideNavigation/>
        <div className='w-full'>
          <TopNavigation/>
          <Table/>
        </div>
      </div>
    </>
  )
}
